version: 0.2

phases:
  install:
    commands:
      - echo "install terraform"
      - wget https://releases.hashicorp.com/terraform/0.15.5/terraform_0.15.5_linux_amd64.zip
      - unzip terraform_0.15.5_linux_amd64.zip
      - sudo mv terraform /usr/local/bin
      - terraform --version
  pre_build:
    commands:
      - echo "Terraform init"
      - terraform init
  build:
    commands:
      - echo Build started on `date`
      - echo "Terraform apply"
      - terraform apply -auto-approve 
#  post_build:
#    commands:
#      - echo Build completed on `date`
#artifacts:
#  files:
#    - target/messageUtil-1.0.jar
